import { GET_QUESTION_LIST_PENDING, GET_QUESTION_LIST_SUCCESS, GET_QUESTION_LIST_FAILED, SET_CANDIDATE_ANSWER, CHANGE_CURRENT_ANSWER } from "./question.actions";
export const QUESTION = {
    GET_QUESTION_LIST_PENDING,
    GET_QUESTION_LIST_SUCCESS,
    GET_QUESTION_LIST_FAILED,
    SET_CANDIDATE_ANSWER,
    CHANGE_CURRENT_ANSWER,
};