export const GET_QUESTION_LIST_PENDING = "GET_QUESTION_LIST_PENDING";
export const GET_QUESTION_LIST_SUCCESS = "GET_QUESTION_LIST_SUCCESS";
export const GET_QUESTION_LIST_FAILED = "GET_QUESTION_LIST_FAILED";
export const SET_CANDIDATE_ANSWER = "SET_CANDIDATE_ANSWER";
export const CHANGE_CURRENT_ANSWER = "CHANGE_CURRENT_ANSWER";